language: node_js
node_js:
  - 10
cache:
  npm: true # this cashes ~/.npm folder on Travis
  directories:
    # we also need to cache folder with Cypress binary
    - ~/.cache

script:
  - npm install
  - npm run build

jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release
      node_js:
        - 10
      deploy:
        provider: script
        script: npx semantic-release
